#!/usr/bin/env bash


###
### Loopback Interfaces
###
# 4 Loopback interfaces
sudo ifconfig lo:0 127.0.0.2 netmask 255.0.0.0 up
sudo ifconfig lo:1 127.0.0.3 netmask 255.0.0.0 up
sudo ifconfig lo:2 127.0.0.4 netmask 255.0.0.0 up


###
### VPP
###

# Restart VPP
sudo service vpp restart

# Add loopback interfaces to VPP (using .2 and .3)
vppctl create host-interface name lo:0
vppctl create host-interface name lo:1

# Set up the LB source IP on host-lo:0 and host-lo:1
# @@@ This line causes bad tcp checksum errors (without going through LB)
# vppctl set int ip address host-lo:0 127.0.0.2/8
vppctl set int ip address host-lo:1 127.0.0.3/8

# Bring these up
vppctl set interface state host-lo:0 up
vppctl set interface state host-lo:1 up


###
### VPP LB
###

# Set up the LB to send from .3
vppctl lb conf ip4-src-address 127.0.0.3 buckets 32

# Set the VIP to .2
vppctl lb vip 127.0.0.2/32 encap gre4

# Add an AS - at .4
vppctl lb as 127.0.0.2/32 127.0.0.4


###
### GRE
###

# Create GRE tunnel in VPP (seems to make no difference at present)
vppctl create gre tunnel src 127.0.0.3 dst 127.0.0.4

# Two options here it seems - neither work...
USE_GRETAP=1
if [[ $USE_GRETAP -ne 0 ]]
then
    # Use gretap
    sudo ip link add gre2 type gretap remote 127.0.0.3 local 127.0.0.4 ttl 255
    sudo ip link set gre2 up

    # Do we need to have a route to 127.0.0.2 through the GRE tunnel?
    sudo ip addr add 127.0.0.2/32 dev gre2
    sudo ip addr add 127.0.0.4/32 dev gre2
else
    sudo ip tunnel add gre1 mode gre remote 127.0.0.3 local 127.0.0.4 ttl 255
    sudo ip link set gre1 up

    # Do we need to have a route to 127.0.0.2 through the GRE tunnel?
    sudo ip addr add 127.0.0.2/32 dev gre1
    sudo ip addr add 127.0.0.4/32 dev gre1
fi


###
### Output the config
###

echo "================================================================"
echo "VPP Interfaces:"
vppctl show interface
echo "================================================================"
echo "VPP LB Config:"
vppctl show lb
echo "...LB VIP Config:"
vppctl show lb vip verbose
echo "================================================================"
echo "FIB Table:"
vppctl show ip fib
