#!/usr/bin/env bash


###
### OS
###
# 4 Loopback interfaces
sudo ifconfig lo:0 127.0.0.2 netmask 255.0.0.0 up
sudo ifconfig lo:1 127.0.0.3 netmask 255.0.0.0 up
sudo ifconfig lo:2 127.0.0.4 netmask 255.0.0.0 up

# Restart VPP
sudo service vpp restart


###
### VPP
###

# Add loopback interfaces to VPP (using .2 and .3)
vppctl create host-interface name lo:0
vppctl create host-interface name lo:1

# Bring these up
vppctl set interface state host-lo:0 up
vppctl set interface state host-lo:1 up


###
### VPP LB
###

# Set up the LB to send from .3
vppctl lb conf ip4-src-address 127.0.0.3 buckets 32

# Set the VIP to .2
vppctl lb vip 127.0.0.2/32 encap gre4

# Add an AS - at .4
vppctl lb as 127.0.0.2/32 127.0.0.4

###
### GRE on receiving end
###

# TODO - maybe this needs to live in another namespace so we can have the (unencapsulated) target as 127.0.0.2?
# sudo ip tunnel add gre1 mode gre remote 127.0.0.3 local 127.0.0.4 ttl 255
# sudo ip link set gre0 up
# sudo ip addr add 10.10.10.2/24 dev gre0

###
### Output the config
###

echo "================================================================"
echo "VPP Interfaces:"
vppctl show interface
echo "================================================================"
echo "VPP LB Config:"
vppctl show lb
echo "...LB VIP Config:"
vppctl show lb vip verbose
