#!/usr/bin/env bash

# @@@ Set up constants file to source...

# Set up trace, try to connect a TCP socket, then output the trace to file
vppctl clear trace
vppctl trace add af-packet-input 20
# Need this running to listen:
# nc -uvlk4 127.0.0.4 3000
if echo -n "DATA!!!\n" | nc -4v -q0 10.0.0.101 3000
then
    echo "SUCCESS!!!"
else
    echo "Failed (netcat rc=$?)"
fi
vppctl show trace > "$(dirname $0)/latest_output"
